params:
  - params.yaml

stages:
  tune:
    cmd:
      python3 core/workflows/ray_tune_rllib.py
    deps:
      - core/workflows/ray_tune_rllib.py
    # outs:
      # - ${ray.results_dir}/${experiment_name}/results.json