ray:
  init: true
  results_dir: data/
tune:
  num_trials: 3
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(levelname)s: %(message)s'
  handlers:
    logfile:
      class: logging.handlers.RotatingFileHandler
      formatter: simple
      backupCount: 3
      maxBytes: 100000
      filename: logs/test_experiment.log
  loggers:
    root:
      level: DEBUG
      handlers:
      - logfile
experiment_name: test_experiment
new: test with modified test script
experiment_metadata_filepath: experiment_metadata.txt
