ray:
  init: true
  results_dir: data/
tune:
  num_trials: 3
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(levelname)s: %(message)s'
  handlers:
    logfile:
      class: logging.handlers.RotatingFileHandler
      formatter: simple
      backupCount: 3
      maxBytes: 10000
      filename: logs/no_name.log
  loggers:
    root:
      level: DEBUG
      handlers:
      - logfile
experiment_name: no_name
